
version: "3"

services:
  web:
    build: ./containers/nginx
    links:
      - phpfpm
    volumes:
      - ./magento:/var/www/html
    ports:
      - 8000:80
         
  phpfpm:
    build: ./containers/php
    volumes:
      - ./magento:/var/www/html
    links:
      - db
    
  db:
    image: percona:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 8001:3306
    env_file: env/mysql.env
        
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
     - 81:80
    env_file: env/pma.env
 
  setup:
    build: ./containers/php
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes:
      - ./magento:/var/www/html
      - ./.composer:/var/www/.composer
    env_file: env/setup.env
    
    
